version: "3"
services:
  recipe-backend:
    build: .
    command: npm run start
    ports:
      - "3000:3000"
    networks:
      - recipe-app

  mongodb:
    container_name: mongodb
    image: mongo:4.2.14
    ports:
      - "27017:27017"
    restart: always
    networks:
      - recipe-app
    hostname: mongodb
    volumes:
      - ~/mongodata:/data/db

networks:
  recipe-app:
    driver: bridge
